# Generated by Django 4.2.29 on 2026-03-17 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='inventory.client'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
