# Generated by Django 4.2.29 on 2026-03-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_quotation_client_alter_quotation_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('service', 'Car service'), ('retail', 'Individuals'), ('shop', 'Auto Parts Shop')], default='retail', max_length=10),
        ),
    ]
