# Generated by Django 4.2.29 on 2026-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='def_discount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
